source = mappings.conf

exec-once = noctalia-shell

input {
    kb_layout = gb
}

$primary = rgb(ffdd33)
$surface = rgb(181818)
$secondary = rgb(96a6c8)
$error = rgb(f43841)

general {
    col.active_border = $primary
    col.inactive_border = $surface
    gaps_in = 4
    gaps_out = 8
}

animations {
    enabled = true
    bezier = easeOut, 0.25, 1, 0.5, 1
    bezier = easeInOut, 0.45, 0, 0.55, 1
    bezier = overshoot, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 2, overshoot, popin 80%
    animation = windowsOut, 1, 2, easeOut, popin 80%
    animation = fade, 1, 2, easeOut
    animation = workspaces, 1, 2, easeInOut, slide
    animation = specialWorkspace, 1, 2, easeInOut, slidevert
}

decoration {
    rounding = 2

    blur {
        enabled = true
        size = 3
        passes = 2
        new_optimizations = true
    }

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(00000055)
    }
}

windowrulev2 = opacity 0.90 override 0.90 override, class:^(dev\.zed\.Zed)$

windowrulev2 = opacity 0.80 override 0.80 override, class:^(com\.mitchellh\.ghostty)$

group {
    col.border_active = $secondary
    col.border_inactive = $surface
    col.border_locked_active = $error
    col.border_locked_inactive = $surface

    groupbar {
        col.active = $secondary
        col.inactive = $surface
        col.locked_active = $error
        col.locked_inactive = $surface
    }
}
